name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: macos-12
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.2"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme WrapLayout -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2'
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.2"
      - uses: actions/checkout@v2
          
      - name: Test
        run: xcodebuild -scheme WrapLayoutTests -resultBundlePath results/FluidInterfaceKitTests.xcresult test -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2' -derivedDataPath ./DerivedData | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/FluidInterfaceKitTests.xcresult
        if: success() || failure()
